// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220706103624_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("EntityLayer.Concrete.CaprazKur", b =>
                {
                    b.Property<string>("DovizKodu")
                        .HasColumnType("text");

                    b.Property<int>("Birim")
                        .HasColumnType("integer");

                    b.Property<double>("CaprazKurDeger")
                        .HasColumnType("double precision");

                    b.Property<string>("DovizCinsiV1")
                        .HasColumnType("text");

                    b.Property<string>("DovizCinsiV2")
                        .HasColumnType("text");

                    b.HasKey("DovizKodu");

                    b.ToTable("CaprazKurs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.DovizKuru", b =>
                {
                    b.Property<string>("DovizKodu")
                        .HasColumnType("text");

                    b.Property<int>("Birim")
                        .HasColumnType("integer");

                    b.Property<double>("DovizAlis")
                        .HasColumnType("double precision");

                    b.Property<string>("DovizCinsi")
                        .HasColumnType("text");

                    b.Property<double>("DovizSatis")
                        .HasColumnType("double precision");

                    b.Property<double>("EfektifAlis")
                        .HasColumnType("double precision");

                    b.Property<double>("EfektifSatis")
                        .HasColumnType("double precision");

                    b.HasKey("DovizKodu");

                    b.ToTable("DovizKurus");
                });
#pragma warning restore 612, 618
        }
    }
}
